from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, BackgroundTasks, Depends, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.event import Event
from app.models.task import Task
from app.models.travel import Travel
from app.models.user import User
from app.services.ai_service import ai_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/briefing", tags=["Briefing"])


# ── Response schemas ───────────────────────────────────────────────────────────


class BriefingResponse(BaseModel):
    greeting: str
    summary: str
    meetings_count: int
    tasks_count: int
    pending_count: int
    events: List[Dict[str, Any]]
    tasks: List[Dict[str, Any]]
    pending_suggestions: List[Dict[str, Any]]
    travel: List[Dict[str, Any]]
    generated_at: str


class BriefingAcceptedResponse(BaseModel):
    message: str
    status: str = "queued"


# ── Helpers ────────────────────────────────────────────────────────────────────


async def _fetch_briefing_data(
    db: AsyncSession,
    user_id,
) -> tuple[list, list, list, list]:
    """Return (events, tasks, travel, pending_suggestions) for a user."""
    now = datetime.now(timezone.utc)
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    today_end = today_start + timedelta(days=1)

    events_result = await db.execute(
        select(Event).where(
            Event.user_id == user_id,
            Event.status.in_(["approved", "synced"]),
            Event.start_time >= today_start,
            Event.start_time < today_end,
        ).order_by(Event.start_time.asc())
    )
    events = [
        {
            "id": str(e.id),
            "title": e.title,
            "start_time": e.start_time.isoformat() if e.start_time else None,
            "end_time": e.end_time.isoformat() if e.end_time else None,
            "location": e.location,
            "attendees": e.attendees,
        }
        for e in events_result.scalars().all()
    ]

    tasks_result = await db.execute(
        select(Task).where(
            Task.user_id == user_id,
            Task.status.in_(["pending", "in_progress"]),
        ).order_by(Task.priority.desc(), Task.due_date.asc().nullslast())
    )
    tasks = [
        {
            "id": str(t.id),
            "title": t.title,
            "priority": t.priority,
            "due_date": t.due_date.isoformat() if t.due_date else None,
            "status": t.status,
        }
        for t in tasks_result.scalars().all()
    ]

    travel_result = await db.execute(
        select(Travel).where(
            Travel.user_id == user_id,
            Travel.status == "upcoming",
            Travel.departure_time >= now,
        ).order_by(Travel.departure_time.asc())
    )
    travel = [
        {
            "id": str(tr.id),
            "type": tr.travel_type,
            "departure": tr.departure_time.isoformat() if tr.departure_time else None,
            "arrival": tr.arrival_time.isoformat() if tr.arrival_time else None,
            "details": tr.details,
        }
        for tr in travel_result.scalars().all()
    ]

    pending_result = await db.execute(
        select(Event).where(
            Event.user_id == user_id,
            Event.status == "pending",
        ).order_by(Event.created_at.desc())
    )
    pending_suggestions = [
        {
            "id": str(e.id),
            "title": e.title,
            "start_time": e.start_time.isoformat() if e.start_time else None,
            "source": e.source,
            "confidence_score": e.confidence_score,
        }
        for e in pending_result.scalars().all()
    ]

    return events, tasks, travel, pending_suggestions


# ── Endpoints ──────────────────────────────────────────────────────────────────


@router.get(
    "/today",
    response_model=BriefingResponse,
    summary="Get today's daily briefing",
)
async def get_today_briefing(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> BriefingResponse:
    """
    Returns a personalised daily briefing for the authenticated user.
    Includes today's events, pending tasks, upcoming travel, and pending suggestions.
    The greeting and summary are generated by AI.
    """
    events, tasks, travel, pending_suggestions = await _fetch_briefing_data(db, current_user.id)

    briefing = await ai_service.generate_daily_briefing(
        events=events,
        tasks=tasks,
        travel=travel,
    )

    return BriefingResponse(
        greeting=briefing.greeting,
        summary=briefing.ai_summary or "Here's your day at a glance.",
        meetings_count=len(events),
        tasks_count=len(tasks),
        pending_count=len(pending_suggestions),
        events=events,
        tasks=tasks,
        travel=travel,
        pending_suggestions=pending_suggestions,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )


@router.post(
    "/generate",
    response_model=BriefingAcceptedResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Force-regenerate today's briefing in the background",
)
async def generate_briefing(
    background_tasks: BackgroundTasks,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> BriefingAcceptedResponse:
    """
    Triggers a background regeneration of the daily briefing via Celery.
    Returns 202 Accepted immediately.
    """
    user_id = str(current_user.id)

    def _trigger_celery():
        try:
            from app.workers.tasks import send_daily_briefings
            # Fire the task for this specific user via a targeted call;
            # the full scheduled task covers all users but we can reuse the logic
            # by triggering the scheduled task (it iterates all active users).
            send_daily_briefings.delay()
        except Exception as exc:
            logger.warning("Failed to queue briefing generation for user %s: %s", user_id, exc)

    background_tasks.add_task(_trigger_celery)

    return BriefingAcceptedResponse(
        message="Briefing generation queued. You will receive a push notification when ready.",
        status="queued",
    )


@router.get(
    "/history",
    summary="Get briefing history for the last 7 days",
)
async def get_briefing_history(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Returns a summary of events and tasks for each of the last 7 days,
    giving a historical view of what was on the user's plate each day.
    """
    now = datetime.now(timezone.utc)
    history = []

    for day_offset in range(7):
        day_start = (now - timedelta(days=day_offset)).replace(
            hour=0, minute=0, second=0, microsecond=0
        )
        day_end = day_start + timedelta(days=1)
        day_label = day_start.strftime("%Y-%m-%d")

        events_result = await db.execute(
            select(Event).where(
                Event.user_id == current_user.id,
                Event.status.in_(["approved", "synced"]),
                Event.start_time >= day_start,
                Event.start_time < day_end,
            ).order_by(Event.start_time.asc())
        )
        day_events = [
            {
                "id": str(e.id),
                "title": e.title,
                "start_time": e.start_time.isoformat() if e.start_time else None,
                "location": e.location,
            }
            for e in events_result.scalars().all()
        ]

        history.append(
            {
                "date": day_label,
                "events_count": len(day_events),
                "events": day_events,
            }
        )

    return {"history": history, "days": 7}
